#Variables
@baseUrl = http://localhost:3333

# Health check
GET {{baseUrl}}/health

###

# GET rooms
# @name getRooms
GET {{baseUrl}}/rooms

###

# POST room
# @name createRoom
POST {{baseUrl}}/room
Content-Type: application/json

{
  "name": "Room Name",
  "description": "Room Description"
}

###
#@roomId = {{getRooms.response.body.$.[0].id}}
@roomId = {{createRoom.response.body.$.roomId}}


###

# GET room questions
# @name getRoomQuestions
GET {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

###

# POST Question
# @name create Question
POST {{baseUrl}}/rooms/{{roomId}}/questions
Content-Type: application/json

{
  "question": "What is your question?"
}